name: release
on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: github
    runs-on: ubuntu-latest
    env:
      BUILDER_NAME: "GitHub Actions"
      BUILDER_EMAIL: noreply@actions.github.com

    steps:

    - name: Set up Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
      id: go

    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: build for platforms
      run: |
        BUILD_GOARCH=amd64 BUILD_GOOS=freebsd make build-artifact
        BUILD_GOARCH=amd64 BUILD_GOOS=linux   make build-artifact
        BUILD_GOARCH=amd64 BUILD_GOOS=darwin  make build-artifact

    - name: create release
      run: make github-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    name: docker
    env:
      BUILDER_NAME: "GitHub Actions"
      BUILDER_EMAIL: actions@noreply.github.com

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mrtazz/certcal:${GITHUB_SHA} --tag mrtazz/certcal:latest

    - name: push to ghcr
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker push mrtazz/certcal:${GITHUB_SHA}
        docker push mrtazz/certcal:latest
        docker logout ghcr.io
